# Generated by Django 5.1.5 on 2025-02-18 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_options_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EditedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_content', models.TextField()),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_posts', to='network.post')),
            ],
        ),
    ]
