# Generated by Django 5.1.5 on 2025-02-19 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_comment_content_alter_like_liker_editedpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-commented_at']},
        ),
    ]
