# Generated by Django 5.1.5 on 2025-02-19 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_post_updated_at_delete_editedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 4, 38, 22, 222779, tzinfo=datetime.timezone.utc)),
        ),
    ]
