# Generated by Django 5.1.5 on 2025-02-19 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_post_options_post_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
