# Generated by Django 5.1.5 on 2025-02-11 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_comment_comment_on_comment_content_comment_create_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
