# Generated by Django 5.1.5 on 2025-02-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_bid_by_bid_bid_for_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_actived',
            field=models.BooleanField(default=False),
        ),
    ]
