# Generated by Django 5.1.5 on 2025-02-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_is_actived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_actived',
            new_name='is_active',
        ),
    ]
