# Generated by Django 5.1.5 on 2025-02-10 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='interested_by',
            field=models.ManyToManyField(related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
